server:
  port: 8090
cors:
  allowedOriginPatterns: "*"
  allowedMethods: "*"
  allowedHeaders: "*"
  exposedHeaders: "*"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/api_gateway
    username: postgres
    password: 123456
  flyway:
    default-schema: api_gateway
